name: Build Ghost Detection APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-android:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 20

    - name: Install Java JDK
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: 17

    - name: Setup Android SDK
      uses: android-actions/setup-android@v2
      with:
        api-level: 34
        build-tools: 34.0.0
        cmake: false
        ndk: false

    - name: Install Cordova
      run: npm install -g cordova@11.0.0

    - name: Install Cordova Plugins
      run: |
        cordova plugin add cordova-plugin-device-motion
        cordova plugin add cordova-plugin-device-orientation
        cordova plugin add cordova-plugin-media
        cordova plugin add cordova-plugin-camera
        cordova plugin add cordova-plugin-file

    - name: Prepare Cordova Android Platform
      run: |
        cordova platform rm android || true
        cordova platform add android@14.1.0

    - name: Copy www files
      run: |
        cp -R www/* platforms/android/app/src/main/assets/www/

    - name: Build Debug APK
      run: |
        cd platforms/android
        ./gradlew assembleDebug

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: ghost-detection-apk
        path: platforms/android/app/build/outputs/apk/debug/app-debug.apk
