name: Build Ghost Detection App (Signed APK + iOS IPA)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-android:
    name: Build Android Release (Signed)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install Cordova
        run: npm install -g cordova

      - name: Prepare Android SDK
        uses: android-actions/setup-android@v2
        with:
          api-level: 34
          target: android-34
          build-tools: 34.0.0

      - name: Install Project Dependencies
        run: npm install

      - name: Add Android Platform
        run: |
          cordova platform remove android || true
          cordova platform add android

      - name: Build Android Release APK
        run: cordova build android --release -- --project=main

      - name: Generate Debug Keystore
        run: |
          keytool -genkey -v -keystore debug.keystore -alias ghostdebug -storepass android -keypass android -dname "CN=Ghost Detection, OU=None, O=None, L=None, S=None, C=None"

      - name: Sign APK
        run: |
          jarsigner -verbose -sigalg SHA1withRSA -digestalg SHA1 -keystore debug.keystore -storepass android -keypass android platforms/android/app/build/outputs/apk/release/app-release-unsigned.apk ghostdebug

      - name: Align APK
        run: |
          $ANDROID_HOME/build-tools/34.0.0/zipalign -v 4 platforms/android/app/build/outputs/apk/release/app-release-unsigned.apk build/ghostdetection-signed.apk

      - name: Upload Signed APK
        uses: actions/upload-artifact@v4
        with:
          name: GhostDetection-release-signed.apk
          path: build/ghostdetection-signed.apk

  build-ios:
    name: Build iOS Debug IPA
    runs-on: macos-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install Cordova
        run: npm install -g cordova

      - name: Install Project Dependencies
        run: npm install

      - name: Add iOS Platform
        run: |
          cordova platform remove ios || true
          cordova platform add ios

      - name: Build iOS Debug for Device
        run: cordova build ios --debug --device -- --project=main

      - name: Archive .app with xcodebuild
        run: |
          mkdir -p build/ios
          xcodebuild -workspace platforms/ios/GhostDetection.xcworkspace \
            -scheme "Ghost Detection" \
            -configuration Debug \
            -destination 'generic/platform=iOS' \
            -archivePath $PWD/build/GhostDetection.xcarchive archive

      - name: Create exportOptions.plist
        run: |
          cat <<EOF > build/ios/exportOptions.plist
          <?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
          <plist version="1.0">
          <dict>
            <key>method</key>
            <string>development</string>
            <key>signingStyle</key>
            <string>manual</string>
            <key>compileBitcode</key>
            <false/>
            <key>destination</key>
            <string>export</string>
          </dict>
          </plist>
          EOF

      - name: Export IPA
        run: |
          xcodebuild -exportArchive \
            -archivePath $PWD/build/GhostDetection.xcarchive \
            -exportOptionsPlist $PWD/build/ios/exportOptions.plist \
            -exportPath $PWD/build/ios

      - name: Upload IPA
        uses: actions/upload-artifact@v4
        with:
          name: GhostDetection-iOS-Debug-IPA
          path: build/ios/GhostDetection.ipa
