name: Cordova APK Build and Sign (Android 15)

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-android:
    runs-on: ubuntu-latest

    env:
      APP_NAME: Ghost Detection
      PACKAGE_NAME: pdgdeplopment.pcdaimaougroup.ghost.detection
      VERSION_CODE: 1
      VERSION_NAME: 1.0.0
      AUTHOR: "パソコン大魔王グループ"
      KEYSTORE_PASSWORD: z@031148
      KEY_ALIAS: PDGDeplopment
      KEY_PASSWORD: z@031148

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Install Cordova
        run: npm install -g cordova

      - name: Create Cordova config.xml if not exists
        run: |
          if [ ! -f config.xml ]; then
            echo "<?xml version='1.0' encoding='utf-8'?>
            <widget id='${PACKAGE_NAME}' version='${VERSION_NAME}' xmlns='http://www.w3.org/ns/widgets' xmlns:cdv='http://cordova.apache.org/ns/1.0'>
              <name>${APP_NAME}</name>
              <description>Cordova App by ${AUTHOR}</description>
              <author>${AUTHOR}</author>
              <content src='index.html'/>
              <preference name='android-minSdkVersion' value='21' />
              <preference name='android-targetSdkVersion' value='35' />
              <preference name='android-compileSdkVersion' value='35' />
              <preference name='BackupWebStorage' value='none'/>
            </widget>" > config.xml
          fi

      - name: Install Android SDK dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y unzip wget
          mkdir -p $HOME/android-sdk/cmdline-tools
          wget https://dl.google.com/android/repository/commandlinetools-linux-9123335_latest.zip -O cmdline-tools.zip
          unzip cmdline-tools.zip -d $HOME/android-sdk/cmdline-tools
          mkdir -p $HOME/android-sdk/cmdline-tools/latest
          mv $HOME/android-sdk/cmdline-tools/cmdline-tools/* $HOME/android-sdk/cmdline-tools/latest/
          echo "export ANDROID_HOME=$HOME/android-sdk" >> $GITHUB_ENV
          echo "export PATH=$HOME/android-sdk/cmdline-tools/latest/bin:$HOME/android-sdk/platform-tools:$PATH" >> $GITHUB_ENV
          yes | $HOME/android-sdk/cmdline-tools/latest/bin/sdkmanager --licenses
          $HOME/android-sdk/cmdline-tools/latest/bin/sdkmanager "platform-tools" "platforms;android-35" "build-tools;35.0.0"

      - name: Add Android platform (Cordova-Android 14)
        run: |
          cordova platform remove android || true
          cordova platform add android@14.0.1

      - name: Install Cordova plugins
        run: |
          cordova plugin add cordova-plugin-device
          cordova plugin add cordova-plugin-dialogs
          cordova plugin add cordova-plugin-geolocation
          cordova plugin add cordova-plugin-media
          cordova plugin add cordova-plugin-camera
          cordova plugin add cordova-plugin-file
          cordova plugin add cordova-plugin-device-motion

      - name: Build unsigned APK (release)
        run: cordova build android --release -- --packageType=apk

      - name: Generate keystore
        run: |
          keytool -genkeypair \
            -alias $KEY_ALIAS \
            -keyalg RSA \
            -keysize 2048 \
            -validity 10000 \
            -keystore my-release-key.keystore \
            -storepass $KEYSTORE_PASSWORD \
            -keypass $KEY_PASSWORD \
            -dname "CN=PDGDeplopment, OU=Development, O=パソコン大魔王グループ, L=Tokyo, ST=Tokyo, C=JP"

      - name: Sign APK with apksigner
        run: |
          $HOME/android-sdk/build-tools/35.0.0/apksigner sign \
            --ks my-release-key.keystore \
            --ks-pass pass:$KEYSTORE_PASSWORD \
            --key-pass pass:$KEY_PASSWORD \
            --out platforms/android/app/build/outputs/apk/release/GhostDetection-release-signed.apk \
            platforms/android/app/build/outputs/apk/release/app-release-unsigned.apk

      - name: Align signed APK
        run: |
          $HOME/android-sdk/build-tools/35.0.0/zipalign -v -p 4 \
            platforms/android/app/build/outputs/apk/release/GhostDetection-release-signed.apk \
            platforms/android/app/build/outputs/apk/release/GhostDetection-release.apk

      - name: Upload Signed APK
        uses: actions/upload-artifact@v4
        with:
          name: GhostDetection-signed-apk
          path: platforms/android/app/build/outputs/apk/release/GhostDetection-release.apk
