name: Cordova APK Build and Sign

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-android:
    runs-on: ubuntu-latest

    env:
      APP_NAME: Ghost Detection
      PACKAGE_NAME: PDGDeplopmet.pcdaimaougroup.Ghost.Detection
      VERSION_CODE: 1
      VERSION_NAME: 1.0.0
      AUTHOR: "パソコン大魔王グループ"
      KEYSTORE_PASSWORD: z@031148
      KEY_ALIAS: PDGDeplopment
      KEY_PASSWORD: z@031148

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install Cordova
        run: npm install -g cordova

      - name: Create Cordova config.xml if not exists
        run: |
          if [ ! -f config.xml ]; then
            echo "<?xml version='1.0' encoding='utf-8'?>
            <widget id='${PACKAGE_NAME}' version='${VERSION_NAME}' xmlns='http://www.w3.org/ns/widgets' xmlns:cdv='http://cordova.apache.org/ns/1.0'>
              <name>${APP_NAME}</name>
              <description>Cordova App by ${AUTHOR}</description>
              <author>${AUTHOR}</author>
              <content src='index.html'/>
              <preference name='android-minSdkVersion' value='21' />
              <preference name='android-targetSdkVersion' value='33' />
              <preference name='BackupWebStorage' value='none'/>
            </widget>" > config.xml
          fi

      - name: Install Android SDK dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y openjdk-11-jdk unzip wget
          wget https://dl.google.com/android/repository/commandlinetools-linux-9123335_latest.zip -O cmdline-tools.zip
          unzip cmdline-tools.zip -d $HOME/android-sdk
          mkdir -p $HOME/android-sdk/cmdline-tools/latest
          mv $HOME/android-sdk/cmdline-tools/* $HOME/android-sdk/cmdline-tools/latest/
          export ANDROID_HOME=$HOME/android-sdk
          export PATH=$ANDROID_HOME/cmdline-tools/latest/bin:$ANDROID_HOME/platform-tools:$PATH
          yes | sdkmanager --licenses
          sdkmanager "platform-tools" "platforms;android-33" "build-tools;33.0.2"

      - name: Add Android platform
        run: |
          cordova platform remove android || true
          cordova platform add android

      - name: Build unsigned APK
        run: cordova build android --release -- --no-sign

      - name: Generate keystore
        run: |
          keytool -genkeypair \
            -alias $KEY_ALIAS \
            -keyalg RSA \
            -keysize 2048 \
            -validity 10000 \
            -keystore my-release-key.keystore \
            -storepass $KEYSTORE_PASSWORD \
            -keypass $KEY_PASSWORD \
            -dname "CN=PDGDeplopment, OU=Development, O=パソコン大魔王グループ, L=Tokyo, ST=Tokyo, C=JP"

      - name: Sign APK
        run: |
          jarsigner -verbose -sigalg SHA1withRSA -digestalg SHA1 \
            -keystore my-release-key.keystore \
            -storepass $KEYSTORE_PASSWORD \
            -keypass $KEY_PASSWORD \
            platforms/android/app/build/outputs/apk/release/app-release-unsigned.apk $KEY_ALIAS

      - name: Align APK
        run: |
          zipalign -v -p 4 \
            platforms/android/app/build/outputs/apk/release/app-release-unsigned.apk \
            platforms/android/app/build/outputs/apk/release/GhostDetection-release.apk

      - name: Upload Signed APK
        uses: actions/upload-artifact@v3
        with:
          name: GhostDetection-signed-apk
          path: platforms/android/app/build/outputs/apk/release/GhostDetection-release.apk
