name: Build Ghost Detection App (Auto Cordova + Signed APK + iOS IPA)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-android:
    name: Build Android Release (Signed)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install Cordova
        run: npm install -g cordova

      - name: Create Cordova Project
        run: |
          rm -rf temp
          cordova create temp PDGAppCreate.pcdaimaougroup.Ghost.Detection "Ghost Detection"
          cp -r main/* temp/www/
          cd temp

      - name: Add Android Platform
        run: |
          cd temp
          cordova platform add android

      - name: Install Cordova Plugins
        run: |
          cd temp
          cordova plugin add cordova-plugin-device
          cordova plugin add cordova-plugin-camera
          cordova plugin add cordova-plugin-media
          cordova plugin add cordova-plugin-file
          cordova plugin add cordova-plugin-whitelist
          cordova plugin add cordova-plugin-geolocation
          cordova plugin add cordova-plugin-network-information

      - name: Build Android Release APK
        run: |
          cd temp
          cordova build android --release

      - name: Generate Debug Keystore
        run: |
          cd temp
          keytool -genkeypair -v -keystore debug.keystore -alias ghostdebug \
            -keyalg RSA -keysize 2048 -validity 10000 \
            -storepass android -keypass android \
            -dname "CN=Ghost Detection, OU=None, O=None, L=None, S=None, C=None"

      - name: Sign APK
        run: |
          cd temp
          jarsigner -verbose -sigalg SHA1withRSA -digestalg SHA1 \
            -keystore debug.keystore \
            -storepass android -keypass android \
            platforms/android/app/build/outputs/apk/release/app-release-unsigned.apk ghostdebug

      - name: Align APK
        run: |
          cd temp
          mkdir -p build
          $ANDROID_HOME/build-tools/34.0.0/zipalign -v 4 \
            platforms/android/app/build/outputs/apk/release/app-release-unsigned.apk \
            build/GhostDetection-signed.apk

      - name: Upload Signed APK
        uses: actions/upload-artifact@v4
        with:
          name: GhostDetection-release-signed.apk
          path: temp/build/GhostDetection-signed.apk

  build-ios:
    name: Build iOS Debug IPA
    runs-on: macos-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install Cordova
        run: npm install -g cordova

      - name: Create Cordova Project
        run: |
          rm -rf temp
          cordova create temp PDGAppCreate.pcdaimaougroup.Ghost.Detection "Ghost Detection"
          cp -r main/* temp/www/
          cd temp

      - name: Add iOS Platform
        run: |
          cd temp
          cordova platform add ios

      - name: Install Cordova Plugins
        run: |
          cd temp
          cordova plugin add cordova-plugin-device
          cordova plugin add cordova-plugin-camera
          cordova plugin add cordova-plugin-media
          cordova plugin add cordova-plugin-file
          cordova plugin add cordova-plugin-whitelist
          cordova plugin add cordova-plugin-geolocation
          cordova plugin add cordova-plugin-network-information

      - name: Build iOS Debug for Device
        run: |
          cd temp
          cordova build ios --debug --device

      - name: Archive .app with xcodebuild
        run: |
          cd temp
          mkdir -p build/ios
          xcodebuild -workspace platforms/ios/GhostDetection.xcworkspace \
            -scheme "Ghost Detection" \
            -configuration Debug \
            -destination 'generic/platform=iOS' \
            -archivePath $PWD/build/GhostDetection.xcarchive archive

      - name: Create exportOptions.plist
        run: |
          cd temp
          cat <<EOF > build/ios/exportOptions.plist
          <?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
          <plist version="1.0">
          <dict>
            <key>method</key>
            <string>development</string>
            <key>signingStyle</key>
            <string>manual</string>
            <key>compileBitcode</key>
            <false/>
            <key>destination</key>
            <string>export</string>
          </dict>
          </plist>
          EOF

      - name: Export IPA
        run: |
          cd temp
          xcodebuild -exportArchive \
            -archivePath $PWD/build/GhostDetection.xcarchive \
            -exportOptionsPlist $PWD/build/ios/exportOptions.plist \
            -exportPath $PWD/build/ios

      - name: Upload IPA
        uses: actions/upload-artifact@v4
        with:
          name: GhostDetection-iOS-Debug-IPA
          path: temp/build/ios/GhostDetection.ipa
